const LIST_PRODUCT_REQUEST = "LP_REQUEST";
const LIST_PRODUCT_SUCCESS = "LP_SUCCESS";
const LIST_PRODUCT_ERROR = "LP_ERROR";

const CREATE_PRODUCT_REQUEST = "CP_REQUEST";
const CREATE_PRODUCT_SUCCESS = "CP_SUCCESS";
const CREATE_PRODUCT_ERROR = "CP_ERROR";

const EDIT_PRODUCT_REQUEST = "EP_REQUEST";
const EDIT_PRODUCT_SUCCESS = "EP_SUCCESS";
const EDIT_PRODUCT_ERROR = "EP_ERROR";

const DELETE_PRODUCT_REQUEST = "DP_REQUEST";
const DELETE_PRODUCT_SUCCESS = "DP_SUCCESS";
const DELETE_PRODUCT_ERROR = "DP_ERROR";

export const PRODUCT_SAGA_TYPES ={
    LIST_PRODUCT_REQUEST ,
    LIST_PRODUCT_SUCCESS,
    LIST_PRODUCT_ERROR,
    CREATE_PRODUCT_REQUEST,
    CREATE_PRODUCT_SUCCESS,
    CREATE_PRODUCT_ERROR,
    EDIT_PRODUCT_REQUEST ,
    EDIT_PRODUCT_ERROR,
    EDIT_PRODUCT_SUCCESS,
    DELETE_PRODUCT_REQUEST,
    DELETE_PRODUCT_SUCCESS,
    DELETE_PRODUCT_ERROR
}